# Generated by Django 5.2.8 on 2025-12-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A unique, identifiable name for the resource.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed information about the resource (features, location, etc.).')),
                ('type', models.CharField(choices=[('ROOM', 'Room/Lecture Hall'), ('EQUIP', 'Equipment (e.g., Projector, Camera)'), ('LAB', 'Laboratory/Specialized Space'), ('VEH', 'Vehicle'), ('OTHER', 'Other')], default='OTHER', help_text='The category of the resource (e.g., Room, Equipment).', max_length=5)),
                ('capacity', models.IntegerField(default=1, help_text='The maximum number of people or concurrent uses allowed.')),
            ],
            options={
                'verbose_name': 'Bookable Resource',
                'verbose_name_plural': 'Bookable Resources',
                'ordering': ['name'],
            },
        ),
    ]
