# Generated by Django 5.2.8 on 2025-12-04 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_bookingrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingrequest',
            options={'ordering': ['start_time'], 'verbose_name': 'Booking Request', 'verbose_name_plural': 'Booking Requests'},
        ),
        migrations.RenameField(
            model_name='bookingrequest',
            old_name='created_at',
            new_name='requested_on',
        ),
        migrations.AddField(
            model_name='resource',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Indicates if the resource is currently active and bookable.'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='end_time',
            field=models.DateTimeField(help_text='The end date and time of the booking.'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='resource',
            field=models.ForeignKey(help_text='The resource or equipment being requested.', on_delete=django.db.models.deletion.CASCADE, related_name='resource_bookings', to='booking.resource'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='start_time',
            field=models.DateTimeField(help_text='The start date and time of the booking.'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='The current approval status of the booking request.', max_length=10),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='user',
            field=models.ForeignKey(help_text='The user who submitted this booking request.', on_delete=django.db.models.deletion.CASCADE, related_name='user_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resource',
            name='capacity',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of people or concurrent uses allowed.'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
