# Generated by Django 5.2.8 on 2025-12-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_bookingrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='payment_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'No Payment Required'), ('PENDING', 'Payment Pending'), ('PAID', 'Payment Completed'), ('FAILED', 'Payment Failed')], default='NOT_REQUIRED', help_text='Payment status for this booking.', max_length=15),
        ),
        migrations.AddField(
            model_name='resource',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost to book this resource (0 for free).', max_digits=10),
        ),
    ]
