# Generated by Django 5.2.8 on 2025-12-06 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_bookingrequest_payment_status_resource_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='capacity',
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='purpose',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='capacity_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='resource',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='payment_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'No Payment Required'), ('PENDING', 'Payment Pending'), ('PAID', 'Payment Completed'), ('FAILED', 'Payment Failed')], default='NOT_REQUIRED', max_length=15),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_bookings', to='booking.resource'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resource',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='resource',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('ROOM', 'Room/Lecture Hall'), ('EQUIP', 'Equipment (e.g., Projector, Camera)'), ('LAB', 'Laboratory/Specialized Space'), ('VEH', 'Vehicle'), ('OTHER', 'Other')], default='OTHER', max_length=5),
        ),
    ]
