# Generated by Django 5.2.8 on 2025-12-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_resource_capacity_bookingrequest_purpose_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='capacity_number',
            new_name='quantity_available',
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('ARCHIVED', 'Archived')], default='PENDING', max_length=10),
        ),
    ]
