# Generated by Django 5.2.8 on 2025-12-07 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_rename_capacity_number_resource_quantity_available_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='quantity_available',
            new_name='quantity',
        ),
    ]
