# Generated by Django 5.2.8 on 2025-12-09 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_usermessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingrequest',
            options={'ordering': ['start_time'], 'permissions': [('can_review_booking', 'Can approve or reject pending bookings')], 'verbose_name': 'Booking Request', 'verbose_name_plural': 'Booking Requests'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['name'], 'permissions': [('can_create_resource', 'Can create new resources'), ('can_delete_resource', 'Can delete existing resources')], 'verbose_name': 'Bookable Resource', 'verbose_name_plural': 'Bookable Resources'},
        ),
    ]
