# Generated by Django 5.2.8 on 2025-12-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_bookingrequest_options_alter_resource_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='purpose',
            field=models.TextField(),
        ),
    ]
